verison: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/source/Calamari"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Pacific/Auckland"
    open-pull-requests-limit: 5
  
  - package-ecosystem: "nuget"
    directory: "/source/Calamari.Aws"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Pacific/Auckland"
    open-pull-requests-limit: 5